plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/app/data/所有对话/主对话/名古屋旅行/dist"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]